if (!require(knitr)) install.packages("knitr")
if (!require(rstan)) install.packages("rstan")
if (!require(igraph)) install.packages("igraph")
if (!require(rgexf)) install.packages("rgexf")
if (!require(bayesplot)) install.packages("bayesplot")
if (!require(ggplot2)) install.packages("ggplot2")